### ISSUE TITLE
demo is down

### ISSUE THREAD

**Issue by a7medo778** [Phyks/ampache_react#35]
hey there,
i am considering migrating my ampache based app from ionic to react native, so i thought i might have a couple of clues from this project.
the hosted version looks to be down though.

**Comment by Phyks** [comment]
What do you mean by "the demo is down"?

To use this app, you need a working Ampache instance with some credentials on it, and this instance has to serve the XML API with CORS header, see https://github.com/Phyks/ampache_react#requirements.

Anyways, this project is not really maintained anymore.

**Comment by a7medo778** [comment]
Mmmm, i thought the hosted version (https://phyks.github.io/ampache_react/) is supposed to work the angular hosted version of airsonic
A.k.a it prompt you to enter your setup credentials to test it out https://airsonic.github.io/airsonic-ui/


Right now i get an empty page

**Comment by Phyks** [comment]
You need the `/public` at the end of the URL. See link next to description under project name: https://phyks.github.io/ampache_react/public/. I've just fixed the `README.md` links.

**Comment by a7medo778** [comment]
mmmm i am getting  "Failed to fetch"
i guess we should concentrate on the laravel update for now
